### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'faerun')

### ISSUE THREAD

**Issue by Skroas** [Julexar/Multi-World-Calendar#3]
whenever I try to use the script I get this error:
TypeError: Cannot read properties of undefined (reading 'faerun')

**Comment by Julexar** [comment]
@Skroas When exactly does that error show up? Does it show up immediately when you use the Command?

Also which Version of the Script are you using?

**Comment by Skroas** [comment]
it shows up on both the roll20 version as well as the version I downloaded here. The v1.0 version. I posted a screenshot so that you can see what it looks like. The bug disables all of my API's.
![Errorssss](https://github.com/Julexar/Multi-World-Calendar/assets/166528144/1f4077af-793a-4b0e-a87a-e37fbebd0b73)

**Comment by Skroas** [comment]
sorry did not mean to close I misclicked!

**Comment by Julexar** [comment]
I'll look into it, thanks - in the meantime use the old version or the Faerûn Calendar Script

**Comment by Skroas** [comment]
hey there, I hate to say it but I'm having the exact same issue with version 1.1 

I hope you're able to figure this out! Good luck!

**Comment by Julexar** [comment]
@Skroas Try resetting the Calendar (`!mwcal --reset`)

It works fine for me

**Comment by Skroas** [comment]
> @Skroas Try resetting the Calendar (`!mwcal --reset`)
> 
> It works fine for me

I would but the entire roll20 API shuts down with the error so there's nothing I can do to try to reset it
