### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'faerun') still happening

### ISSUE THREAD

**Issue by Skroas** [Julexar/Multi-World-Calendar#5]
hey there, I hate to say it but I'm having the exact same issue with version 1.1

I hope you're able to figure this out! Good luck!

**Comment by Julexar** [comment]
@Skroas Try resetting the Calendar (`!mwcal --reset`)

It works perfectly fine on a fresh install

**Comment by Skroas** [comment]
I would but the entire roll20 API shuts down with the error so there's nothing I can do to try to reset it. I did enter the command just in case with the script enabled but nothing happens. I'm really confused.

**Comment by Julexar** [comment]
Does the API shut down immediately or only when you run `!mwcal`?

(Since it worked fine until I ran the command in 1.0)

**Comment by Julexar** [comment]
Otherwise try manually resetting it by removing the `!` in the `checkInstall` function

**Comment by Skroas** [comment]
all scripts are immediately disabled as soon as I save the script and the roll20 API restarts. I don't have an opportunity put any command inputs for any of my scripts because it disables them all. I've tried installing it by itself as well to see if it was interfearing with anything else but nothing seems to work.

**Comment by Julexar** [comment]
@Skroas try manually resetting it by removing the `!` in the `checkInstall` function

**Comment by Julexar** [comment]
It should hopefully fix the issue - if not, then please invite me to the Game as a GM and I'll see what I can do

**Comment by Skroas** [comment]
> It should hopefully fix the issue - if not, then please invite me to the Game as a GM and I'll see what I can do

https://app.roll20.net/join/17010343/mki7xA here's the invite for a testing game. I did try to remove the ! but it did nothing. I'm having the same issue here as my main game. I'll give you GM once you're in!

**Comment by Julexar** [comment]
@Skroas That's really weird. In my test game, it works perfectly fine. Did you install anything else before my script?

**Comment by Skroas** [comment]
nothing. That game is brand new...

**Comment by Julexar** [comment]
@Skroas Do you have Discord so we can communicate faster?

**Comment by Skroas** [comment]
I do is your ID the same as on here?

**Comment by Julexar** [comment]
@Skroas  Yep - julexar
